version: '3'
services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management
    hostname: rabbitmq-test    # specify your hostname here
    volumes:
        - "./rabbitmq-data:/var/lib/rabbitmq/mnesia/"
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq

networks:
  rabbitmq:
    driver: bridge